global:
  slack_api_url: 'https://hooks.slack.com/services/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'

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: [app, group, env]
  receiver: 'ops-forum-api'
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m

receivers:
- name: 'ops-forum-api'
  slack_configs:
  - channel: '#forum-api'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.app }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Summary:* {{ .Annotations.summary }}
     
     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} â€¢ *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}
